SELECT 
  OBS.UNIT_ID OBS_UNIT_ID,
  OBS.NAME OBS_NAME,
  DD.BUCIO_GROUP,
  SEC_GROUP.GROUP_NAME BUCIO_GROUP_NAME,
  EM.ID EXEC_ID,
  EM.FULL_NAME EXEC_NAME,
  FINANCIAL.BUDGET,
  FINANCIAL.FORECAST,
  FINANCIAL.FORECAST_YTD,
  FINANCIAL.YEAR_END,
  FINANCIAL.YTD,
  FINANCIAL.NO_BUDGET_IR,
  I.CODE INVESTMENT_ID,
  I.NAME INVESTMENT_NAME,
  PROJECT_TYPE.NAME PROJECT_TYPE,
  PC.DESCRIPTION CLASS,
  PM.USER_ID PROJECT_MANAGER_ID,
  PM.FULL_NAME PROJECT_MANAGER,
  PROGRESS.NAME PROGRESS,
  STATUS.NAME STATUS,
  I.SCHEDULE_START,
  P.PLANNED_DATE,
  P.REVISED_END_DATE,
  I.DESCRIPTION,
  I.STATUS_COMMENT
FROM
  WARM01.INV_INVESTMENTS I,
  WARM01.INV_PROJECTS IP,
  WARM01.ODF_CA_PROJECT P,
  WARM01.PAC_MNT_PROJECTS F,
  WARM01.SRM_RESOURCES PM,
  WARM01.SRM_RESOURCES EM,
  WARM01.DEPARTMENTS D,
  WARM01.ODF_CA_DEPARTMENT DD,
  WARM01.PROJCLASS PC,
  (SELECT LOOKUP_CODE ID,NAME FROM WARM01.CMN_LOOKUPS_V WHERE LOOKUP_TYPE='OBJ_IDEA_PROJECT_TYPE' AND LANGUAGE_CODE='en') PROJECT_TYPE,
  (SELECT LOOKUP_ENUM ID, NAME NAME FROM WARM01.CMN_LOOKUPS_V WHERE LOOKUP_TYPE='INVESTMENT_OBJ_PROGRESS' AND LANGUAGE_CODE='en') PROGRESS,
  (SELECT LOOKUP_ENUM ID, NAME NAME FROM WARM01.CMN_LOOKUPS_V WHERE LOOKUP_TYPE='INVESTMENT_STATUS_INDICATOR' AND LANGUAGE_CODE='en') STATUS,
  (SELECT ID, GROUP_NAME FROM WARM01.CMN_SEC_GROUPS_V WHERE LANGUAGE_CODE = 'en') SEC_GROUP,
  (SELECT INVESTMENTS_OBS_UNITS.INVESTMENT_ID,
       BUSINESS_UNITS.UNIT_ID,
       BUSINESS_UNITS.UNIQUE_NAME,
       BUSINESS_UNITS.NAME
  FROM (SELECT INV_OBS_UNITS.INVESTMENT_ID, INV_OBS_UNITS.OBS_UNIT
          FROM WARM01.INV_OBS_ONLY_V INV_OBS_UNITS,
               WARM01.PRJ_OBS_UNITS OBS_UNITS,
               WARM01.PRJ_OBS_TYPES OBS_TYPES
         WHERE     INV_OBS_UNITS.OBS_UNIT = OBS_UNITS.ID
               AND OBS_UNITS.TYPE_ID = OBS_TYPES.ID
               AND OBS_TYPES.ID = 5000001) INVESTMENTS_OBS_UNITS,
       (SELECT UNIT_ID, UNIQUE_NAME, NAME
          FROM WARM01.OBS_UNITS_V
         WHERE DEPTH = 3 AND UNIT_MODE = 'OBS_UNIT_AND_ANCESTORS') BUSINESS_UNITS
 WHERE INVESTMENTS_OBS_UNITS.OBS_UNIT = BUSINESS_UNITS.UNIT_ID(+)) OBS,
 (SELECT PROJECT_ID, SUM (BUDGET) BUDGET, SUM (FORECAST) FORECAST, SUM (FORECAST_YTD) FORECAST_YTD,
     CASE 
       WHEN SUM (BUDGET) = 0 THEN 0 
       ELSE 100 * (SUM (FORECAST) / SUM (BUDGET)) 
     END YEAR_END,
     CASE 
       WHEN SUM (BUDGET) = 0 THEN 0 
       ELSE 100 * (SUM (FORECAST_YTD) / SUM (BUDGET)) 
     END YTD,
     CASE
       WHEN SUM (BUDGET) = 0 AND SUM (FORECAST) > 0 THEN 1
       ELSE 0 
     END NO_BUDGET_IR
FROM (SELECT INVESTMENTS.ID PROJECT_ID,
             -- budget costs
             CASE
                WHEN PLANS.PLAN_TYPE_CODE = 'BUDGET' AND CLASSES.TRANSCLASS = 'Labor'
                THEN NVL (ROUND ( COSTS.SLICE * (TO_DATE (COSTS.FINISH_DATE) - TO_DATE (COSTS.START_DATE)),2),0)
                ELSE 0
             END BUDGET,
             -- forecast costs
             CASE
                WHEN PLANS.PLAN_TYPE_CODE = 'FORECAST' AND CLASSES.TRANSCLASS = 'Labor'
                THEN NVL(ROUND ( COSTS.SLICE * (TO_DATE (COSTS.FINISH_DATE) - TO_DATE (COSTS.START_DATE)),2),0)
                ELSE 0
             END FORECAST,
             -- forecast ytd costs
             CASE
                WHEN PLANS.PLAN_TYPE_CODE = 'FORECAST' AND CLASSES.TRANSCLASS = 'Labor' AND COSTS.START_DATE <= {?date_param}
                THEN ROUND ( COSTS.SLICE * (TO_DATE (COSTS.FINISH_DATE) - TO_DATE (COSTS.START_DATE)),2)
                ELSE 0
             END FORECAST_YTD
        FROM WARM01.ODF_SSL_CST_DTL_COST COSTS,
             WARM01.FIN_COST_PLAN_DETAILS DETAILS,
             WARM01.TRANSCLASS CLASSES,
             WARM01.FIN_PLANS PLANS,
             WARM01.INV_INVESTMENTS INVESTMENTS
       WHERE     COSTS.PRJ_OBJECT_ID = DETAILS.ID
             AND DETAILS.PLAN_ID = PLANS.ID
             AND DETAILS.TRANSCLASS_ID = CLASSES.ID
             AND PLANS.OBJECT_ID = INVESTMENTS.ID
             AND PLANS.IS_PLAN_OF_RECORD = 1
             AND TO_CHAR (COSTS.START_DATE, 'YYYY') = TO_CHAR ({?date_param}, 'YYYY'))
GROUP BY PROJECT_ID) FINANCIAL
WHERE
  I.ID = P.ID
  AND I.ID = F.ID
  AND I.ID = IP.PRID
  AND I.ID = OBS.INVESTMENT_ID
  AND I.ID = PROJECT_ID(+)
  AND F.DEPARTCODE = D.DEPARTCODE
  AND F.CLASS = PC.PROJCLASS
  AND D.ID = DD.ID
  AND DD.BUCIO_GROUP = SEC_GROUP.ID(+)
  AND D.BRM_ID = EM.USER_ID(+)
  AND I.MANAGER_ID = PM.USER_ID(+)
  AND I.PROGRESS = PROGRESS.ID(+)
  AND I.STATUS_INDICATOR = STATUS.ID(+)
  AND P.OBJ_REQUEST_TYPE = PROJECT_TYPE.ID(+)
  AND I.ENTITY_CODE = 'CID'
  AND I.ODF_OBJECT_CODE = 'project'
  AND I.IS_ACTIVE = 1
  AND P.OBJ_REQUEST_TYPE NOT IN ('customerbank')
  AND IP.IS_TEMPLATE = 0
  AND (
        PM.USER_ID = CASE WHEN {?manager_id} = 0 THEN PM.USER_ID ELSE {?manager_id} END
      )
  AND (
        NVL(DD.BUCIO_GROUP,0) = CASE WHEN {?bucio_id} = 0 THEN NVL(DD.BUCIO_GROUP,0) ELSE {?bucio_id} END
      )
  AND (
        NVL(D.BRM_ID,0) = CASE WHEN {?exec_id} = 0 THEN NVL(D.BRM_ID,0) ELSE {?exec_id} END
      )