SELECT 
  I.ID INVESTMENT_ID,
  I.CODE PROJECT_ID,
  I.NAME PROJECT_NAME,
  L5.NAME DIVISION,
  CASE WHEN L5.NAME = D.SHORTDESC THEN NULL ELSE D.SHORTDESC END TEAM,
  R.USER_ID USER_ID,
  R.ID RESOURCE_ID,
  R.FULL_NAME RESOURCE_NAME,
  R.IS_ACTIVE RESOURCE_IS_ACTIVE,
  R.IS_EXTERNAL RESOURCE_IS_EXTERNAL,
  CASE WHEN R.PERSON_TYPE = 300 THEN 'Employee' ELSE 'Consultant' END RESOURCE_TYPE,
  RD.PRISROLE RESOURCE_IS_ROLE,
  RR.ID ROLE_ID,
  RR.FULL_NAME ROLE_NAME,
  NVL (S.SLICE, 0) UNITS,
  S.SLICE_DATE,
  'ACTUALS' ROW_TYPE
FROM PRJ_BLB_SLICES S, PRJ_BLB_SLICEREQUESTS Q, PRASSIGNMENT A, PRTEAM T, SRM_RESOURCES R, PRJ_RESOURCES RD, SRM_RESOURCES RR, PAC_MNT_RESOURCES FR, PRTASK TK, INV_INVESTMENTS I,
DEPARTMENTS D,
(SELECT O.UNIT_ID,
                    O.UNIQUE_NAME,
                    O.NAME,
                    DV.DEPARTMENT_MANAGER_ID
               FROM WARM01.OBS_UNITS_V O, DEPARTMENTS DV
              WHERE     O.LINKED_UNIT_ID = DV.OBS_UNIT_ID
                    AND O.DEPTH = 5
                    AND O.UNIT_MODE = 'OBS_UNIT_AND_ANCESTORS') L5
WHERE S.SLICE_REQUEST_ID = Q.ID
      AND S.PRJ_OBJECT_ID = A.PRID
      AND A.TEAM_ID = T.PRID
      AND T.PRRESOURCEID = R.ID
      AND R.ID = RD.PRID
      AND R.ID = FR.ID
      AND FR.DEPARTCODE = D.DEPARTCODE
      AND D.OBS_UNIT_ID = L5.UNIT_ID
      AND RD.PRPRIMARYROLEID = RR.ID(+)
      AND A.PRTASKID = TK.PRID
      AND TK.PRPROJECTID = I.ID
      -- monthly periods
      AND Q.PERIOD = 3
      -- actual hours curve
      AND Q.FIELD = 0
      AND S.SLICE_DATE BETWEEN TRUNC(SYSDATE,'YYYY') AND SYSDATE
      AND R.ENTITY_CODE = 'CID'
      AND FR.TRANSCLASS = 'Labor'
      AND I.CODE = 'BJ9'