SELECT
  CC_CD,CC_NAME,ROLE_NAME,
  -- actuals
  SUM("01_UNITS_A") "01_UNITS_A",
  SUM("02_UNITS_A") "02_UNITS_A",
  SUM("03_UNITS_A") "03_UNITS_A",
  SUM("04_UNITS_A") "04_UNITS_A",
  SUM("05_UNITS_A") "05_UNITS_A",
  SUM("06_UNITS_A") "06_UNITS_A",
  SUM("07_UNITS_A") "07_UNITS_A",
  SUM("08_UNITS_A") "08_UNITS_A",
  SUM("09_UNITS_A") "09_UNITS_A",
  SUM("10_UNITS_A") "10_UNITS_A",
  SUM("11_UNITS_A") "11_UNITS_A",
  SUM("12_UNITS_A") "12_UNITS_A",
  SUM("SUM_UNITS_A") "SUM_UNITS_A",
  SUM("SUM_UNITS_A") / TO_NUMBER(TO_CHAR(SYSDATE,'MM')) "YTD_UNITS_A",
  -- soft
  SUM("01_UNITS_S") "01_UNITS_S",
  SUM("02_UNITS_S") "02_UNITS_S",
  SUM("03_UNITS_S") "03_UNITS_S",
  SUM("04_UNITS_S") "04_UNITS_S",
  SUM("05_UNITS_S") "05_UNITS_S",
  SUM("06_UNITS_S") "06_UNITS_S",
  SUM("07_UNITS_S") "07_UNITS_S",
  SUM("08_UNITS_S") "08_UNITS_S",
  SUM("09_UNITS_S") "09_UNITS_S",
  SUM("10_UNITS_S") "10_UNITS_S",
  SUM("11_UNITS_S") "11_UNITS_S",
  SUM("12_UNITS_S") "12_UNITS_S",
  SUM("SUM_UNITS_S") "SUM_UNITS_S",
  SUM("SUM_UNITS_S") / TO_NUMBER(TO_CHAR(SYSDATE,'MM')) "YTD_UNITS_S",
  -- hard
  SUM("01_UNITS_H") "01_UNITS_H",
  SUM("02_UNITS_H") "02_UNITS_H",
  SUM("03_UNITS_H") "03_UNITS_H",
  SUM("04_UNITS_H") "04_UNITS_H",
  SUM("05_UNITS_H") "05_UNITS_H",
  SUM("06_UNITS_H") "06_UNITS_H",
  SUM("07_UNITS_H") "07_UNITS_H",
  SUM("08_UNITS_H") "08_UNITS_H",
  SUM("09_UNITS_H") "09_UNITS_H",
  SUM("10_UNITS_H") "10_UNITS_H",
  SUM("11_UNITS_H") "11_UNITS_H",
  SUM("12_UNITS_H") "12_UNITS_H",
  SUM("SUM_UNITS_H") "SUM_UNITS_H",
  SUM("SUM_UNITS_H") / TO_NUMBER(TO_CHAR(SYSDATE,'MM')) "YTD_UNITS_H"
  
FROM (

SELECT 
  DTL.UNIT_ID,
  DTL.CC_CD,
  DTL.CC_NAME,
  DTL.ROLE_NAME,
  -- actuals
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 01 AND DTL.ROW_TYPE = 'ACTUALS' THEN DTL.UNITS ELSE 0 END "01_UNITS_A",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 02 AND DTL.ROW_TYPE = 'ACTUALS' THEN DTL.UNITS ELSE 0 END "02_UNITS_A",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 03 AND DTL.ROW_TYPE = 'ACTUALS' THEN DTL.UNITS ELSE 0 END "03_UNITS_A",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 04 AND DTL.ROW_TYPE = 'ACTUALS' THEN DTL.UNITS ELSE 0 END "04_UNITS_A",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 05 AND DTL.ROW_TYPE = 'ACTUALS' THEN DTL.UNITS ELSE 0 END "05_UNITS_A",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 06 AND DTL.ROW_TYPE = 'ACTUALS' THEN DTL.UNITS ELSE 0 END "06_UNITS_A",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 07 AND DTL.ROW_TYPE = 'ACTUALS' THEN DTL.UNITS ELSE 0 END "07_UNITS_A",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 08 AND DTL.ROW_TYPE = 'ACTUALS' THEN DTL.UNITS ELSE 0 END "08_UNITS_A",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 09 AND DTL.ROW_TYPE = 'ACTUALS' THEN DTL.UNITS ELSE 0 END "09_UNITS_A",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 10 AND DTL.ROW_TYPE = 'ACTUALS' THEN DTL.UNITS ELSE 0 END "10_UNITS_A",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 11 AND DTL.ROW_TYPE = 'ACTUALS' THEN DTL.UNITS ELSE 0 END "11_UNITS_A",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 12 AND DTL.ROW_TYPE = 'ACTUALS' THEN DTL.UNITS ELSE 0 END "12_UNITS_A",
  CASE WHEN DTL.ROW_TYPE = 'ACTUALS' THEN DTL.UNITS ELSE 0 END "SUM_UNITS_A",
  -- soft
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 01 AND DTL.ROW_TYPE = 'SOFT' THEN DTL.UNITS ELSE 0 END "01_UNITS_S",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 02 AND DTL.ROW_TYPE = 'SOFT' THEN DTL.UNITS ELSE 0 END "02_UNITS_S",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 03 AND DTL.ROW_TYPE = 'SOFT' THEN DTL.UNITS ELSE 0 END "03_UNITS_S",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 04 AND DTL.ROW_TYPE = 'SOFT' THEN DTL.UNITS ELSE 0 END "04_UNITS_S",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 05 AND DTL.ROW_TYPE = 'SOFT' THEN DTL.UNITS ELSE 0 END "05_UNITS_S",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 06 AND DTL.ROW_TYPE = 'SOFT' THEN DTL.UNITS ELSE 0 END "06_UNITS_S",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 07 AND DTL.ROW_TYPE = 'SOFT' THEN DTL.UNITS ELSE 0 END "07_UNITS_S",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 08 AND DTL.ROW_TYPE = 'SOFT' THEN DTL.UNITS ELSE 0 END "08_UNITS_S",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 09 AND DTL.ROW_TYPE = 'SOFT' THEN DTL.UNITS ELSE 0 END "09_UNITS_S",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 10 AND DTL.ROW_TYPE = 'SOFT' THEN DTL.UNITS ELSE 0 END "10_UNITS_S",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 11 AND DTL.ROW_TYPE = 'SOFT' THEN DTL.UNITS ELSE 0 END "11_UNITS_S",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 12 AND DTL.ROW_TYPE = 'SOFT' THEN DTL.UNITS ELSE 0 END "12_UNITS_S",
  CASE WHEN DTL.ROW_TYPE = 'SOFT' THEN DTL.UNITS ELSE 0 END "SUM_UNITS_S",
  -- hard
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 01 AND DTL.ROW_TYPE = 'HARD' THEN DTL.UNITS ELSE 0 END "01_UNITS_H",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 02 AND DTL.ROW_TYPE = 'HARD' THEN DTL.UNITS ELSE 0 END "02_UNITS_H",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 03 AND DTL.ROW_TYPE = 'HARD' THEN DTL.UNITS ELSE 0 END "03_UNITS_H",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 04 AND DTL.ROW_TYPE = 'HARD' THEN DTL.UNITS ELSE 0 END "04_UNITS_H",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 05 AND DTL.ROW_TYPE = 'HARD' THEN DTL.UNITS ELSE 0 END "05_UNITS_H",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 06 AND DTL.ROW_TYPE = 'HARD' THEN DTL.UNITS ELSE 0 END "06_UNITS_H",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 07 AND DTL.ROW_TYPE = 'HARD' THEN DTL.UNITS ELSE 0 END "07_UNITS_H",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 08 AND DTL.ROW_TYPE = 'HARD' THEN DTL.UNITS ELSE 0 END "08_UNITS_H",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 09 AND DTL.ROW_TYPE = 'HARD' THEN DTL.UNITS ELSE 0 END "09_UNITS_H",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 10 AND DTL.ROW_TYPE = 'HARD' THEN DTL.UNITS ELSE 0 END "10_UNITS_H",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 11 AND DTL.ROW_TYPE = 'HARD' THEN DTL.UNITS ELSE 0 END "11_UNITS_H",
  CASE WHEN TO_CHAR(DTL.SLICE_DATE,'MM') = 12 AND DTL.ROW_TYPE = 'HARD' THEN DTL.UNITS ELSE 0 END "12_UNITS_H",
  CASE WHEN DTL.ROW_TYPE = 'HARD' THEN DTL.UNITS ELSE 0 END "SUM_UNITS_H",
  DTL.ROW_TYPE

FROM (

SELECT 
  L5.UNIT_ID,
  L5.UNIQUE_NAME CC_CD,
  L5.NAME CC_NAME,
  RR.FULL_NAME ROLE_NAME,
  NVL (S.SLICE, 0) UNITS,
  S.SLICE_DATE,
  'ACTUALS' ROW_TYPE
FROM PRJ_BLB_SLICES S, PRJ_BLB_SLICEREQUESTS Q, PRASSIGNMENT A, PRTEAM T, SRM_RESOURCES R, PRJ_RESOURCES RD, SRM_RESOURCES RR, PAC_MNT_RESOURCES FR, PRTASK TK, INV_INVESTMENTS I,
DEPARTMENTS D,
(SELECT O.UNIT_ID,
                    O.UNIQUE_NAME,
                    O.NAME,
                    DV.DEPARTMENT_MANAGER_ID
               FROM WARM01.OBS_UNITS_V O, DEPARTMENTS DV
              WHERE     O.LINKED_UNIT_ID = DV.OBS_UNIT_ID
                    AND O.DEPTH = 5
                    AND O.UNIT_MODE = 'OBS_UNIT_AND_ANCESTORS') L5
WHERE S.SLICE_REQUEST_ID = Q.ID
      AND S.PRJ_OBJECT_ID = A.PRID
      AND A.TEAM_ID = T.PRID
      AND T.PRRESOURCEID = R.ID
      AND R.ID = RD.PRID
      AND R.ID = FR.ID
      AND FR.DEPARTCODE = D.DEPARTCODE
      AND D.OBS_UNIT_ID = L5.UNIT_ID
      AND RD.PRPRIMARYROLEID = RR.ID(+)
      AND A.PRTASKID = TK.PRID
      AND TK.PRPROJECTID = I.ID
      -- monthly periods
      AND Q.PERIOD = 3
      -- actual hours curve
      AND Q.FIELD = 0
      AND S.SLICE_DATE BETWEEN TRUNC(SYSDATE,'YYYY') AND SYSDATE
      AND R.ENTITY_CODE = 'CID'
      AND FR.TRANSCLASS = 'Labor'
  
UNION ALL

SELECT 
  L5.UNIT_ID,
  L5.UNIQUE_NAME CC_CD,
  L5.NAME CC_NAME,
  RR.FULL_NAME ROLE_NAME,
  NVL (S.SLICE, 0) UNITS,
  S.SLICE_DATE,
  'HARD' ROW_TYPE
FROM PRJ_BLB_SLICES_M_HARDALC S, PRJ_BLB_SLICEREQUESTS Q, PRTEAM T, SRM_RESOURCES R, PRJ_RESOURCES RD, SRM_RESOURCES RR, PAC_MNT_RESOURCES FR, INV_INVESTMENTS I, DEPARTMENTS D,
(SELECT O.UNIT_ID,
                    O.UNIQUE_NAME,
                    O.NAME,
                    DV.DEPARTMENT_MANAGER_ID
               FROM WARM01.OBS_UNITS_V O, DEPARTMENTS DV
              WHERE     O.LINKED_UNIT_ID = DV.OBS_UNIT_ID
                    AND O.DEPTH = 5
                    AND O.UNIT_MODE = 'OBS_UNIT_AND_ANCESTORS') L5
WHERE S.SLICE_REQUEST_ID = Q.ID
      AND S.PRJ_OBJECT_ID = T.PRID
      AND T.PRRESOURCEID = R.ID
      AND T.PRPROJECTID = I.ID
      AND R.ID = RD.PRID
      AND R.ID = FR.ID
      AND FR.DEPARTCODE = D.DEPARTCODE
      AND D.OBS_UNIT_ID = L5.UNIT_ID
      AND RD.PRPRIMARYROLEID = RR.ID(+)
      -- monthly periods
      AND Q.PERIOD = 3
      -- actual hours curve
      AND Q.FIELD = 22
      AND S.SLICE_DATE BETWEEN TRUNC(SYSDATE,'YYYY') AND SYSDATE
      AND R.ENTITY_CODE = 'CID'
      AND FR.TRANSCLASS = 'Labor'
  
UNION ALL

SELECT 
  L5.UNIT_ID,
  L5.UNIQUE_NAME CC_CD,
  L5.NAME CC_NAME,
  RR.FULL_NAME ROLE_NAME,
  NVL (S.SLICE, 0) UNITS,
  S.SLICE_DATE,
  'SOFT' ROW_TYPE
FROM PRJ_BLB_SLICES S, PRJ_BLB_SLICEREQUESTS Q, PRTEAM T, SRM_RESOURCES R, PRJ_RESOURCES RD, SRM_RESOURCES RR, PAC_MNT_RESOURCES FR, INV_INVESTMENTS I, DEPARTMENTS D,
(SELECT O.UNIT_ID,
                    O.UNIQUE_NAME,
                    O.NAME,
                    DV.DEPARTMENT_MANAGER_ID
               FROM WARM01.OBS_UNITS_V O, DEPARTMENTS DV
              WHERE     O.LINKED_UNIT_ID = DV.OBS_UNIT_ID
                    AND O.DEPTH = 5
                    AND O.UNIT_MODE = 'OBS_UNIT_AND_ANCESTORS') L5
WHERE S.SLICE_REQUEST_ID = Q.ID
      AND S.PRJ_OBJECT_ID = T.PRID
      AND T.PRRESOURCEID = R.ID
      AND T.PRPROJECTID = I.ID
      AND R.ID = RD.PRID
      AND R.ID = FR.ID
      AND FR.DEPARTCODE = D.DEPARTCODE
      AND D.OBS_UNIT_ID = L5.UNIT_ID
      AND RD.PRPRIMARYROLEID = RR.ID(+)
      -- monthly periods
      AND Q.PERIOD = 3
      -- actual hours curve
      AND Q.FIELD = 4
      AND S.SLICE_DATE BETWEEN TRUNC(SYSDATE,'YYYY') AND SYSDATE
      AND R.ENTITY_CODE = 'CID'
      AND FR.TRANSCLASS = 'Labor') DTL
      WHERE DTL.UNIT_ID IN (SELECT LINKED_UNIT_ID FROM OBS_UNITS_V WHERE UNIT_ID = 5000523 AND UNIT_MODE = 'OBS_UNIT_AND_CHILDREN')
      )
      
GROUP BY CC_CD,CC_NAME,ROLE_NAME
ORDER BY CC_CD, ROLE_NAME