SELECT D.DEPARTCODE, D.DESCRIPTION, G.GROUP_NAME BUCIO_GROUP, L3.NAME DEPARTMENT_NAME
  FROM DEPARTMENTS D,
       ODF_CA_DEPARTMENT DD,
       OBS_UNITS_V O,
       (SELECT * FROM CMN_SEC_GROUPS_V WHERE LANGUAGE_CODE = 'en') G,
       (SELECT UNIT_ID, UNIQUE_NAME, NAME
          FROM WARM01.OBS_UNITS_V
         WHERE DEPTH = 1 AND UNIT_MODE = 'OBS_UNIT_AND_ANCESTORS') L1,
         (SELECT UNIT_ID, UNIQUE_NAME, NAME
          FROM WARM01.OBS_UNITS_V
         WHERE DEPTH = 3 AND UNIT_MODE = 'OBS_UNIT_AND_ANCESTORS') L3
 WHERE D.ID = DD.ID 
       AND D.OBS_UNIT_ID = O.LINKED_UNIT_ID
       AND D.OBS_UNIT_ID = L1.UNIT_ID
       AND D.OBS_UNIT_ID = L3.UNIT_ID
       AND DD.BUCIO_GROUP = G.ID(+)
       AND L1.UNIQUE_NAME = 'cid_external'
       AND O.DEPTH = 5
       AND O.UNIT_MODE = 'OBS_UNIT_ONLY'