  SELECT P.UNIQUE_NAME PROJECT_ID,
         P.NAME PROJECT_NAME,
         P.DEPARTCODE PROJECT_DEPARTMENT,
         O.LEVEL1_NAME PROJECT_OBS_LEVEL_1,
         O.LEVEL2_NAME PROJECT_OBS_LEVEL_2,
         O.LEVEL3_NAME PROJECT_OBS_LEVEL_3,
         O.LEVEL4_NAME PROJECT_OBS_LEVEL_4,
         O.LEVEL5_NAME PROJECT_OBS_LEVEL_5,
         O.LEVEL6_NAME PROJECT_OBS_LEVEL_6,
         O.LEVEL7_NAME PROJECT_OBS_LEVEL_7,
         O.LEVEL8_NAME PROJECT_OBS_LEVEL_8,
         O.LEVEL9_NAME PROJECT_OBS_LEVEL_9,
         O.LEVEL10_NAME PROJECT_OBS_LEVEL_10,
         M.UNIQUE_NAME PROJECT_MANAGER_ID,
         M.FULL_NAME PROJECT_MANAGER,
         A.ATTRIBUTE_CODE AUDIT_ATTRIBUTE,
         A.VALUE_BEFORE AUDIT_VALUE_BEFORE,
         A.VALUE_AFTER AUDIT_VALUE_AFTER,
         A.OPERATION_CODE AUDIT_OPERATION,
         A.CREATED_DATE,
         R.FULL_NAME CREATED_BY
    FROM WARM01.CMN_AUDITS A,
         WARM01.SRM_RESOURCES R,
         WARM01.SRM_RESOURCES M,
         WARM01.SRM_WORK_PROJECTS_V P,
         WARM01.DEPARTMENTS D,
         (SELECT OBS_UNIT_ID,
                 LEVEL1_NAME,
                 LEVEL2_NAME,
                 LEVEL3_NAME,
                 LEVEL4_NAME,
                 LEVEL5_NAME,
                 LEVEL6_NAME,
                 LEVEL7_NAME,
                 LEVEL8_NAME,
                 LEVEL9_NAME,
                 LEVEL10_NAME
            FROM WARM01.NBI_DIM_OBS OBS
           WHERE OBS_TYPE_ID = 5000001) O
   WHERE     A.CREATED_BY = R.USER_ID
         AND A.OBJECT_ID = P.ID
         AND P.DEPARTCODE = D.DEPARTCODE
         AND D.OBS_UNIT_ID = O.OBS_UNIT_ID
         AND P.MANAGER_ID = M.USER_ID(+)
         AND A.OBJECT_CODE = 'project'
         AND ATTRIBUTE_CODE IN ('department_code', 'name', 'unique_code')
         AND P.IS_TEMPLATE = 0
ORDER BY A.CREATED_DATE DESC