SELECT 

@SELECT:DIM:USER_DEF:IMPLIED:COST_PLAN:INVESTMENT_ID:INVESTMENT_ID@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:INVESTMENT_NAME:INVESTMENT_NAME@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:INVESTMENT_TYPE:INVESTMENT_TYPE@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:PLAN_ID:PLAN_ID@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:PLAN_NAME:PLAN_NAME@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:TYPE_OF_PLAN:TYPE_OF_PLAN@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:PERIOD_TYPE:PERIOD_TYPE@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:PLAN_OF_RECORD:PLAN_OF_RECORD@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:GROUP_BY:GROUP_BY@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:SUB_GROUP_BY:SUB_GROUP_BY@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:TRANSCLASS:TRANSCLASS@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:CHARGE_CODE:CHARGE_CODE@,

@SELECT:DIM:USER_DEF:IMPLIED:PERIOD:PERIOD_NAME:PERIOD_GROUP@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:PERIOD:PERIOD_NAME:PERIOD_NAME@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:PERIOD:START_DATE:START_DATE@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:PERIOD:FINISH_DATE:FINISH_DATE@,

@SELECT:METRIC:USER_DEF:IMPLIED:UNITS_PLAN:UNITS_PLAN@,
@SELECT:METRIC:USER_DEF:IMPLIED:COST_PLAN:COST_PLAN@,
@SELECT:METRIC:USER_DEF:IMPLIED:REVENUE_PLAN:REVENUE_PLAN@
FROM (

SELECT 
  COST.INVESTMENT_ID,
  COST.INVESTMENT_NAME,
  COST.INVESTMENT_TYPE,
  COST.PLAN_ID,
  COST.PLAN_NAME,
  COST.TYPE_OF_PLAN,
  COST.PERIOD_TYPE,
  COST.PLAN_OF_RECORD,
  GRP_BY.NAME GROUP_BY,
  SUB_GRP_BY.NAME SUB_GROUP_BY,
  TRANS.TRANSCLASS,
  CODE.PRNAME CHARGE_CODE,
  BIZ.PERIOD_NAME,
  COST.START_DATE,
  COST.FINISH_DATE,
  NVL(UNIT.SLICE,0) UNITS_PLAN,
  NVL(COST.SLICE,0) COST_PLAN,
  NVL(REVENUE.SLICE,0) REVENUE_PLAN FROM (
    SELECT 
      PRJ_OBJECT_ID,TRANSCLASS_ID,
      PRCHARGECODE_ID,INV.CODE INVESTMENT_ID,
      ENTITY_CODE,INV.NAME INVESTMENT_NAME,
      INV.ODF_OBJECT_CODE INVESTMENT_TYPE,
      PLAN.CODE PLAN_ID,
      PLAN.NAME PLAN_NAME,
      PLAN.PLAN_TYPE_CODE TYPE_OF_PLAN,
      PERIOD_TYPE_CODE PERIOD_TYPE,
      IS_PLAN_OF_RECORD PLAN_OF_RECORD,
      PLAN_BY_1_CODE,
      PLAN_BY_2_CODE,
      SSL.START_DATE,
      SSL.FINISH_DATE,
      ROUND((SSL.FINISH_DATE-SSL.START_DATE)*SUM(SSL.SLICE),2) SLICE 
    FROM 
      ODF_SSL_CST_DTL_COST SSL,
      INV_INVESTMENTS INV,
      FIN_PLANS PLAN,
      FIN_COST_PLAN_DETAILS DETAILS 
    WHERE 
      INV.ODF_OBJECT_CODE = 'project' AND 
      INV.ID = PLAN.OBJECT_ID AND
      PLAN.ID = DETAILS.PLAN_ID AND 
      DETAILS.ID = SSL.PRJ_OBJECT_ID AND 
      PLAN_TYPE_CODE = 'BUDGET' AND 
      IS_PLAN_OF_RECORD=1 
    GROUP BY 
      INV.CODE,
      INV.NAME,
      INV.ODF_OBJECT_CODE,
      PLAN.CODE,
      PLAN.NAME,
      PLAN.PLAN_TYPE_CODE,
      PERIOD_TYPE_CODE,
      IS_PLAN_OF_RECORD,
      ENTITY_CODE,
      START_DATE,
      FINISH_DATE,
      PLAN_BY_2_CODE,
      (SSL.START_DATE-SSL.FINISH_DATE),
      PLAN_BY_1_CODE,PRJ_OBJECT_ID,
      TRANSCLASS_ID,PRCHARGECODE_ID) COST, 
      (
        SELECT 
          PRJ_OBJECT_ID,
          TRANSCLASS_ID,
          PRCHARGECODE_ID,
          INV.CODE INVESTMENT_ID,
          ENTITY_CODE,INV.NAME INVESTMENT_NAME,
          INV.ODF_OBJECT_CODE INVESTMENT_TYPE,
          PLAN.CODE PLAN_ID,
          PLAN.NAME PLAN_NAME,
          PLAN.PLAN_TYPE_CODE TYPE_OF_PLAN,
          PERIOD_TYPE_CODE PERIOD_TYPE,
          IS_PLAN_OF_RECORD PLAN_OF_RECORD,
          PLAN_BY_1_CODE,
          PLAN_BY_2_CODE,
          SSL.START_DATE,
          SSL.FINISH_DATE,
          ROUND((SSL.FINISH_DATE-SSL.START_DATE)*SUM(SSL.SLICE),2) SLICE 
        FROM 
          ODF_SSL_CST_DTL_UNITS SSL,
          INV_INVESTMENTS INV,
          FIN_PLANS PLAN,
          FIN_COST_PLAN_DETAILS DETAILS 
        WHERE 
          INV.ODF_OBJECT_CODE = 'project' AND 
          INV.ID = PLAN.OBJECT_ID AND
          PLAN.ID = DETAILS.PLAN_ID AND 
          DETAILS.ID = SSL.PRJ_OBJECT_ID AND 
          PLAN_TYPE_CODE = 'BUDGET' AND 
          IS_PLAN_OF_RECORD=1 
        GROUP BY 
          ENTITY_CODE,
          INV.CODE,
          INV.NAME,
          INV.ODF_OBJECT_CODE,
          PLAN.CODE,PLAN.NAME,
          PLAN.PLAN_TYPE_CODE,
          PERIOD_TYPE_CODE,
          IS_PLAN_OF_RECORD,
          PLAN_BY_1_CODE,
          PLAN_BY_2_CODE,
          START_DATE,
          FINISH_DATE,
          (SSL.START_DATE-SSL.FINISH_DATE),
          PRJ_OBJECT_ID,
          TRANSCLASS_ID,
          PRCHARGECODE_ID
      ) UNIT, 
      (
        SELECT 
          PRJ_OBJECT_ID,
          TRANSCLASS_ID,
          PRCHARGECODE_ID,
          ENTITY_CODE,
          INV.CODE INVESTMENT_ID,
          INV.NAME INVESTMENT_NAME,
          INV.ODF_OBJECT_CODE INVESTMENT_TYPE,
          PLAN.CODE PLAN_ID,
          PLAN.NAME PLAN_NAME,
          PLAN.PLAN_TYPE_CODE TYPE_OF_PLAN,
          PERIOD_TYPE_CODE PERIOD_TYPE,
          IS_PLAN_OF_RECORD PLAN_OF_RECORD,
          PLAN_BY_1_CODE,
          PLAN_BY_2_CODE,
          SSL.START_DATE,
          SSL.FINISH_DATE,
          ROUND((SSL.FINISH_DATE-SSL.START_DATE)*SUM(SSL.SLICE),2) SLICE 
        FROM 
          ODF_SSL_CST_DTL_REV SSL,
          INV_INVESTMENTS INV,
          FIN_PLANS PLAN,
          FIN_COST_PLAN_DETAILS DETAILS 
        WHERE 
          INV.ODF_OBJECT_CODE = 'project' AND 
          INV.ID = PLAN.OBJECT_ID AND
          PLAN.ID = DETAILS.PLAN_ID AND 
          DETAILS.ID = SSL.PRJ_OBJECT_ID AND 
          PLAN_TYPE_CODE = 'BUDGET' AND 
          IS_PLAN_OF_RECORD=1 
        GROUP BY 
          ENTITY_CODE,
          INV.CODE,
          INV.NAME,
          INV.ODF_OBJECT_CODE,
          PLAN.CODE,PLAN.NAME,
          PLAN.PLAN_TYPE_CODE,
          PERIOD_TYPE_CODE,
          IS_PLAN_OF_RECORD,
          START_DATE,
          FINISH_DATE,
          PLAN_BY_1_CODE,
          PLAN_BY_2_CODE,
          (SSL.START_DATE-SSL.FINISH_DATE),
          PRJ_OBJECT_ID,
          TRANSCLASS_ID,
          PRCHARGECODE_ID) REVENUE, 
      (
        SELECT 
          LOOKUP_CODE,
          NAME 
        FROM 
          CMN_LOOKUPS_V 
        WHERE 
          LOOKUP_TYPE='FIN_PLAN_BY_TYPE' AND 
          LANGUAGE_CODE='en') GRP_BY, 
      (
        SELECT 
          LOOKUP_CODE,
          NAME 
        FROM 
          CMN_LOOKUPS_V 
        WHERE 
          LOOKUP_TYPE='FIN_PLAN_BY_TYPE' AND 
          LANGUAGE_CODE='en') 
      SUB_GRP_BY, 
      ENTITY ENT,BIZ_COM_PERIODS BIZ, 
      TRANSCLASS TRANS, 
      PRCHARGECODE CODE 
    WHERE 
      COST.PLAN_ID = unit.PLAN_ID(+) AND 
      COST.start_date=unit.start_date(+) AND 
      COST.PLAN_ID=REVENUE.PLAN_ID(+) AND 
      COST.start_date=REVENUE.start_date(+) AND 
      GRP_BY.LOOKUP_CODE =COST.PLAN_BY_1_CODE AND 
      SUB_GRP_BY.LOOKUP_CODE=COST.PLAN_BY_2_CODE AND 
      COST.ENTITY_CODE=ENT.ENTITY AND 
      BIZ.START_DATE=COST.START_DATE AND 
      BIZ.ENTITY_ID=ENT.ID AND 
      TRANS.ID=COST.TRANSCLASS_ID AND
      CODE.PRID=COST.PRCHARGECODE_ID 
    ORDER BY PERIOD_NAME) 
WHERE @FILTER@