SELECT 
  INVESTMENTS.ID INVESTMENT_PRID,
  INVESTMENTS.CODE INVESTMENT_ID,
  INVESTMENTS.ENTITY_CODE,
  INVESTMENTS.NAME INVESTMENT_NAME,
  INVESTMENTS.ODF_OBJECT_CODE INVESTMENT_TYPE,
  INVESTMENTS.IS_ACTIVE,
  INVESTMENTS.MANAGER_ID,
  PROJECT_MANAGERS.FULL_NAME MANAGER_NAME,
  INVESTMENTS.IS_OPEN_FOR_TE,
  OBS_DEPARTMENTS.DEPARTMENT_TYPE,
  OBS_DEPARTMENTS.BUSINESS_UNIT_ID,
  OBS_DEPARTMENTS.BUSINESS_UNIT_NAME,
  PLANS.CODE PLAN_ID,
  PLANS.NAME PLAN_NAME,
  PLANS.DESCRIPTION PLAN_DESCRIPTION,
  PLANS.REVISION PLAN_REVISION,
  PLANS.PLAN_TYPE_CODE PLAN_TYPE,
  PLANS.PERIOD_TYPE_CODE PLAN_PERIOD,
  PLANS.IS_PLAN_OF_RECORD,
  PLAN_GROUP.NAME PLAN_BY_GROUP,
  PLAN_SUBGROUP.NAME PLAN_BY_SUBGROUP,
  CHARGE_CODES.PRNAME CHARGECODE_NAME,
  TRANSACTION_CLASSES.DESCRIPTION TRANCLASS_NAME,
  ROLES.NAME ROLE_NAME,
  PLAN_VALUES.START_DATE,
  PLAN_VALUES.FINISH_DATE,
  PLAN_VALUES.UNITS,
  PLAN_VALUES.COSTS
FROM 
  WARM01.INV_INVESTMENTS INVESTMENTS,
  WARM01.FIN_PLANS PLANS,
  WARM01.FIN_COST_PLAN_DETAILS DETAILS,
  WARM01.TRANSCLASS TRANSACTION_CLASSES,
  WARM01.PRCHARGECODE CHARGE_CODES,
  WARM01.SRM_RESOURCES PROJECT_MANAGERS,
  (SELECT PRJ_OBJECT_ID,START_DATE,FINISH_DATE,SUM(UNITS) UNITS,SUM(COSTS) COSTS FROM (SELECT PRJ_OBJECT_ID,START_DATE,FINISH_DATE,ROUND((FINISH_DATE-START_DATE)*SUM(SLICE),2) UNITS,0 COSTS,0 ACTUALS FROM WARM01.ODF_SSL_CST_DTL_UNITS GROUP BY PRJ_OBJECT_ID,START_DATE,FINISH_DATE UNION SELECT PRJ_OBJECT_ID,START_DATE,FINISH_DATE,0 UNITS,ROUND((FINISH_DATE-START_DATE)*SUM(SLICE),2) COSTS,0 ACTUALS FROM WARM01.ODF_SSL_CST_DTL_COST GROUP BY PRJ_OBJECT_ID,START_DATE,FINISH_DATE) GROUP BY PRJ_OBJECT_ID,START_DATE,FINISH_DATE) PLAN_VALUES,
  (SELECT LOOKUP_CODE ID,NAME FROM WARM01.CMN_LOOKUPS_V WHERE LOOKUP_TYPE='FIN_PLAN_BY_TYPE' AND LANGUAGE_CODE='en') PLAN_GROUP,
  (SELECT LOOKUP_CODE ID,NAME FROM WARM01.CMN_LOOKUPS_V WHERE LOOKUP_TYPE='FIN_PLAN_BY_TYPE' AND LANGUAGE_CODE='en') PLAN_SUBGROUP,
  (SELECT A.PRID ID,B.FULL_NAME NAME FROM WARM01.PRJ_RESOURCES A,WARM01.SRM_RESOURCES B WHERE A.PRID = B.ID AND PRISROLE = 1) ROLES,
  (SELECT INVESTMENTS_OBS_UNITS.INVESTMENT_ID,
       DEPARTMENT_TYPES.NAME DEPARTMENT_TYPE,
       CASE
          WHEN BUSINESS_UNITS.UNIT_ID IS NULL THEN '6101'
          ELSE BUSINESS_UNITS.UNIQUE_NAME
       END
          BUSINESS_UNIT_ID,
       CASE
          WHEN BUSINESS_UNITS.UNIT_ID IS NULL THEN 'Corporate Information'
          ELSE BUSINESS_UNITS.NAME
       END
          BUSINESS_UNIT_NAME
  FROM (SELECT INV_OBS_UNITS.INVESTMENT_ID, INV_OBS_UNITS.OBS_UNIT
          FROM WARM01.INV_OBS_ONLY_V INV_OBS_UNITS,
               WARM01.PRJ_OBS_UNITS OBS_UNITS,
               WARM01.PRJ_OBS_TYPES OBS_TYPES
         WHERE     INV_OBS_UNITS.OBS_UNIT = OBS_UNITS.ID
               AND OBS_UNITS.TYPE_ID = OBS_TYPES.ID
               AND OBS_TYPES.ID = 5000001) INVESTMENTS_OBS_UNITS,
       (SELECT UNIT_ID, UNIQUE_NAME, NAME
          FROM WARM01.OBS_UNITS_V
         WHERE DEPTH = 1 AND UNIT_MODE = 'OBS_UNIT_AND_ANCESTORS') DEPARTMENT_TYPES,
       (SELECT UNIT_ID, UNIQUE_NAME, NAME
          FROM WARM01.OBS_UNITS_V
         WHERE DEPTH = 3 AND UNIT_MODE = 'OBS_UNIT_AND_ANCESTORS') BUSINESS_UNITS
 WHERE INVESTMENTS_OBS_UNITS.OBS_UNIT = DEPARTMENT_TYPES.UNIT_ID(+)
       AND INVESTMENTS_OBS_UNITS.OBS_UNIT = BUSINESS_UNITS.UNIT_ID(+)) OBS_DEPARTMENTS
WHERE 
  INVESTMENTS.ID = PLANS.OBJECT_ID AND
  INVESTMENTS.MANAGER_ID = PROJECT_MANAGERS.USER_ID(+) AND
  INVESTMENTS.ID = OBS_DEPARTMENTS.INVESTMENT_ID(+) AND
  PLANS.ID = DETAILS.PLAN_ID AND 
  DETAILS.ID = PLAN_VALUES.PRJ_OBJECT_ID AND
  DETAILS.PRROLE_ID = ROLES.ID(+) AND
  PLANS.PLAN_BY_1_CODE = PLAN_GROUP.ID(+) AND
  PLANS.PLAN_BY_2_CODE = PLAN_SUBGROUP.ID(+) AND
  DETAILS.TRANSCLASS_ID = TRANSACTION_CLASSES.ID(+) AND
  DETAILS.PRCHARGECODE_ID = CHARGE_CODES.PRID(+)