SELECT
  @SELECT:DIM:USER_DEF:IMPLIED:COST_PLAN:ROWNUM:ROW_ID@,
  @SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:INVESTMENT_ID:INVESTMENT_ID@,
  @SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:INVESTMENT_NAME:INVESTMENT_NAME@,
  @SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:MANAGER_NAME:MANAGER_NAME@,
  @SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:PLAN_ID:PLAN_ID@,
  @SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:PLAN_NAME:PLAN_NAME@,
  @SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:PLAN_DESCRIPTION:PLAN_DESCRIPTION@,
  @SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:PLAN_REVISION:PLAN_REVISION@,
  @SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:PLAN_STATUS:PLAN_STATUS@,
  @SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:PLAN_CREATED_ON:PLAN_CREATED_ON@,
  @SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:PLAN_CREATED_BY:PLAN_CREATED_BY@,
  @SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:PLAN_UPDATED_ON:PLAN_UPDATED_ON@,
  @SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:PLAN_UPDATED_BY:PLAN_UPDATED_BY@,
  @SELECT:DIM_PROP:USER_DEF:IMPLIED:COST_PLAN:PLAN_OF_RECORD:PLAN_OF_RECORD@,
  @SELECT:METRIC:USER_DEF:IMPLIED:UNITS:UNITS@,
  @SELECT:METRIC:USER_DEF:IMPLIED:COSTS:COSTS@
FROM (
  SELECT
    INVESTMENT_ID,
    INVESTMENT_NAME,
    MANAGER_NAME,
    PLAN_ID,
    PLAN_NAME,
    PLAN_DESCRIPTION,
    PLAN_REVISION,
    PLAN_STATUS,
    PLAN_CREATED_ON,
    PLAN_CREATED_BY,
    PLAN_UPDATED_ON,
    PLAN_UPDATED_BY,
    CASE WHEN IS_PLAN_OF_RECORD = 1 THEN 'Y' ELSE 'N' END AS PLAN_OF_RECORD,
    SUM(UNITS) UNITS,
    SUM(COSTS) COSTS
  FROM (
    SELECT 
      INVESTMENTS.ID INVESTMENT_PRID,
      INVESTMENTS.CODE INVESTMENT_ID,
      INVESTMENTS.ENTITY_CODE,
      INVESTMENTS.NAME INVESTMENT_NAME,
      INVESTMENTS.ODF_OBJECT_CODE INVESTMENT_TYPE,
      INVESTMENTS.IS_ACTIVE,
      RESOURCES.FULL_NAME MANAGER_NAME,
      INVESTMENTS.IS_OPEN_FOR_TE,
      PLANS.CODE PLAN_ID,
      PLANS.NAME PLAN_NAME,
      PLANS.DESCRIPTION PLAN_DESCRIPTION,
      PLANS.REVISION PLAN_REVISION,
      PLANS.PLAN_TYPE_CODE PLAN_TYPE,
      PLANS.PERIOD_TYPE_CODE PLAN_PERIOD,
      PLANS.IS_PLAN_OF_RECORD,
      PLANS.STATUS_CODE PLAN_STATUS,
      PLANS.CREATED_DATE PLAN_CREATED_ON,
      RESOURCE_CREATES.FULL_NAME PLAN_CREATED_BY,
      PLANS.LAST_UPDATED_DATE PLAN_UPDATED_ON,
      RESOURCE_UPDATES.FULL_NAME PLAN_UPDATED_BY,
      PLAN_GROUP.NAME PLAN_BY_GROUP,
      PLAN_SUBGROUP.NAME PLAN_BY_SUBGROUP,
      CHARGE_CODES.PRNAME CHARGECODE_NAME,
      TRANSACTION_CLASSES.DESCRIPTION TRANCLASS_NAME,
      ROLES.NAME ROLE_NAME,
      PLAN_VALUES.START_DATE,
      PLAN_VALUES.FINISH_DATE,
      PLAN_VALUES.UNITS,
      PLAN_VALUES.COSTS
    FROM 
      WARM01.INV_INVESTMENTS INVESTMENTS,
      WARM01.FIN_PLANS PLANS,
      WARM01.FIN_COST_PLAN_DETAILS DETAILS,
      WARM01.TRANSCLASS TRANSACTION_CLASSES,
      WARM01.PRCHARGECODE CHARGE_CODES,
      WARM01.SRM_RESOURCES RESOURCES,
      WARM01.SRM_RESOURCES RESOURCE_CREATES,
      WARM01.SRM_RESOURCES RESOURCE_UPDATES,
      (SELECT PRJ_OBJECT_ID,START_DATE,FINISH_DATE,SUM(UNITS) UNITS,SUM(COSTS) COSTS FROM (SELECT PRJ_OBJECT_ID,START_DATE,FINISH_DATE,ROUND((FINISH_DATE-START_DATE)*SUM(SLICE),2) UNITS,0 COSTS,0 ACTUALS FROM WARM01.ODF_SSL_CST_DTL_UNITS GROUP BY PRJ_OBJECT_ID,START_DATE,FINISH_DATE UNION SELECT PRJ_OBJECT_ID,START_DATE,FINISH_DATE,0 UNITS,ROUND((FINISH_DATE-START_DATE)*SUM(SLICE),2) COSTS,0 ACTUALS FROM WARM01.ODF_SSL_CST_DTL_COST GROUP BY PRJ_OBJECT_ID,START_DATE,FINISH_DATE) GROUP BY PRJ_OBJECT_ID,START_DATE,FINISH_DATE) PLAN_VALUES,
      (SELECT LOOKUP_CODE ID,NAME FROM WARM01.CMN_LOOKUPS_V WHERE LOOKUP_TYPE='FIN_PLAN_BY_TYPE' AND LANGUAGE_CODE='en') PLAN_GROUP,
      (SELECT LOOKUP_CODE ID,NAME FROM WARM01.CMN_LOOKUPS_V WHERE LOOKUP_TYPE='FIN_PLAN_BY_TYPE' AND LANGUAGE_CODE='en') PLAN_SUBGROUP,
      (SELECT A.PRID ID,B.FULL_NAME NAME FROM WARM01.PRJ_RESOURCES A,WARM01.SRM_RESOURCES B WHERE A.PRID = B.ID AND PRISROLE = 1) ROLES
    WHERE 
      INVESTMENTS.ID = PLANS.OBJECT_ID AND
      INVESTMENTS.MANAGER_ID = RESOURCES.USER_ID(+) AND
      PLANS.ID = DETAILS.PLAN_ID AND 
      DETAILS.ID = PLAN_VALUES.PRJ_OBJECT_ID AND
      DETAILS.PRROLE_ID = ROLES.ID(+) AND
      PLANS.PLAN_BY_1_CODE = PLAN_GROUP.ID(+) AND
      PLANS.PLAN_BY_2_CODE = PLAN_SUBGROUP.ID(+) AND
      PLANS.CREATED_BY = RESOURCE_CREATES.USER_ID(+) AND
      PLANS.LAST_UPDATED_BY = RESOURCE_UPDATES.USER_ID(+) AND
      DETAILS.TRANSCLASS_ID = TRANSACTION_CLASSES.ID(+) AND
      DETAILS.PRCHARGECODE_ID = CHARGE_CODES.PRID(+)
    )
  WHERE
    ENTITY_CODE = 'CID' AND
    PLAN_TYPE = 'BUDGET' AND
    TRANCLASS_NAME = 'Labor' AND
    INVESTMENT_ID = 'BJ9'
  GROUP BY
    INVESTMENT_ID,
    INVESTMENT_NAME,
    MANAGER_NAME,
    PLAN_ID,
    PLAN_NAME,
    PLAN_DESCRIPTION,
    PLAN_REVISION,
    IS_PLAN_OF_RECORD,
    PLAN_CREATED_ON,
    PLAN_CREATED_BY,
    PLAN_UPDATED_ON,
    PLAN_UPDATED_BY,
    PLAN_STATUS
  ORDER BY
    INVESTMENT_ID,
    PLAN_REVISION)