SELECT
  TEAMS.SLICE_STATUS,
  PROJECTS.ID PROJECT_ID,
  PROJECTS.UNIQUE_NAME PROJECT_CODE,
  PROJECTS.NAME PROJECT_NAME,
  TO_CHAR(SLICES.SLICE_DATE,'YYYY-MM-DD') START_DATE,
  TO_CHAR(LAST_DAY(SLICES.SLICE_DATE),'YYYY-MM-DD') END_DATE,
  SUM(SLICES.SLICE) UNITS,
  ROUND(SUM(SLICES.SLICE)*93.09,2) COST
FROM
  WARM01.PRJ_BLB_SLICES SLICES,
  WARM01.PRJ_BLB_SLICEREQUESTS REQUESTS,
  WARM01.PRTEAM TEAMS,
  WARM01.SRM_PROJECTS PROJECTS,
  WARM01.SRM_RESOURCES RESOURCES
WHERE
  REQUESTS.ID = SLICES.SLICE_REQUEST_ID
  AND SLICES.PRJ_OBJECT_ID = TEAMS.PRID
  AND TEAMS.PRPROJECTID = PROJECTS.ID
  AND TEAMS.PRRESOURCEID = RESOURCES.ID
  /* PLANS PRIOR TO YEAR 2010 ARE ASSUMED TO BE NOT SUPPORTED */
  AND TO_NUMBER(TO_CHAR(SLICES.SLICE_DATE,'YYYY')) > 2010
  AND REQUESTS.FIELD = 4
  AND REQUESTS.PERIOD = 3
  AND REQUESTS.IS_ACTIVE = 1
  AND REQUESTS.IS_TEMPLATE = 0
  AND PROJECTS.UNIQUE_NAME = 'I05'
GROUP BY
  TEAMS.SLICE_STATUS,
  PROJECTS.ID,
  PROJECTS.UNIQUE_NAME,
  PROJECTS.NAME,
  SLICES.SLICE_DATE