SELECT
  INV_INVESTMENTS.ID AS INVESTMENT_ID,
  INV_PROJECTS.PRUSERTEXT1 LEGACY_PROGRAM_ID,
  INV_INVESTMENTS.ODF_OBJECT_CODE INVESTMENT_TYPE,
  INV_PROJECTS.IS_TEMPLATE,
  INV_PROJECTS.IS_PROGRAM,
  INV_INVESTMENTS.STATUS,
  INV_INVESTMENTS.CODE AS INVESTMENT_CODE,
  INV_INVESTMENTS.NAME AS INVESTMENT_NAME,
  INV_INVESTMENTS.SCHEDULE_START,
  INV_INVESTMENTS.SCHEDULE_FINISH,
  INV_INVESTMENTS.DESCRIPTION,
  INV_INVESTMENTS.STATUS_COMMENT,
  PRJ_OBS_UNITS.ID AS DEPT_ID,
  PRJ_OBS_UNITS.NAME AS DEPT_NM,
  PRJ_OBS_TYPES.ID AS DEPT_TYPE_ID,
  PRJ_OBS_TYPES.NAME AS DEPT_TYPE
FROM 
  WARM01.PRJ_OBS_UNITS,
  WARM01.PRJ_OBS_TYPES,
  WARM01.PRJ_OBS_ASSOCIATIONS, 
  WARM01.INV_INVESTMENTS,
  WARM01.INV_PROJECTS
WHERE
  PRJ_OBS_UNITS.ID = PRJ_OBS_ASSOCIATIONS.UNIT_ID AND
  PRJ_OBS_UNITS.TYPE_ID = PRJ_OBS_TYPES.ID AND
  INV_INVESTMENTS.ID = PRJ_OBS_ASSOCIATIONS.RECORD_ID AND
  INV_INVESTMENTS.ID = INV_PROJECTS.PRID
