SELECT
  FACTS.RESOURCE_CODE,
  FACTS.LAST_NAME,
  FACTS.FIRST_NAME,
  FACTS.ROLE_NAME,
  FACTS.DEPARTMENT,
  FACTS.DEPARTMENT_NAME,
  FACTS.LOCATION,
  FACTS.MANAGER_FIRST_NAME,
  FACTS.MANAGER_LAST_NAME,
  UPDATED_BY.FULL_NAME UPDATED_BY,
  UPDATED_BY.LAST_UPDATED_DATE UPDATED_AT
FROM 
  WARM01.NBI_RESOURCE_CURRENT_FACTS FACTS,
  WARM01.SRM_RESOURCES RESOURCES,
  WARM01.SRM_RESOURCES UPDATED_BY
WHERE
  FACTS.RESOURCE_ID = RESOURCES.ID AND
  RESOURCES.LAST_UPDATED_BY = UPDATED_BY.USER_ID AND
    FACTS.ENTITY = 'CID' AND
    FACTS.EXTERNAL_OR_INTERNAL = 0 AND
    FACTS.IS_ROLE = 0 AND
    LENGTH(FACTS.RESOURCE_CODE) = 16