  SELECT MAX (P.ID) COST_PLAN_ID, P.OBJECT_ID INVESTMENT_ID
    FROM WARM01.FIN_PLANS P
   WHERE     SUBSTR (P.NAME, 6, 9) IN ('Submitted', 'submitted')
         AND P.PLAN_TYPE_CODE = 'BUDGET'
GROUP BY P.OBJECT_ID