SELECT 
  P.UUID,
  P.INVESTMENT_ID,
  R.CLIENTCLASS,
  R.PROJECTCLASS,
  R.WIPCLASS,
  P.DATE_VAL,
  P.DATE_UID,
  R.RESOURCE_CODE,
  CASE 
    WHEN R.PROJECTCLASS IN ('FIXED','CIOWNER') THEN 
      CASE WHEN P.AMOUNT IS NULL OR P.AMOUNT = 0 
        THEN 0 
        ELSE ROUND((R.AMOUNT/P.AMOUNT)*NVL(B.AMOUNT,0),2) 
      END
    WHEN R.PROJECTCLASS IN ('TM') THEN R.AMOUNT
    WHEN R.PROJECTCLASS IN ('BASELINE') THEN 0
    ELSE 0
  END RECOVERED_AMOUNT
FROM 
  CID_SP_PROJECT_ACTUAL_SUM P,
  CID_SP_RESOURCE_ACTUAL_PROJECT R,
  CID_SP_PROJECT_BUDGET_SUM B
WHERE
      P.UUID = R.UUID(+)
  AND P.UUID = B.UUID(+)
  AND P.DATE_VAL <= (SELECT TO_DATE (
          CASE
             WHEN CYCLE_DY_OF_MO_NO BETWEEN 1 AND 9
             THEN
                '0' || CYCLE_DY_OF_MO_NO
             ELSE
                TO_CHAR (CYCLE_DY_OF_MO_NO)
          END
          || TO_CHAR (CYCLE_YR_NO),
          'MMYYYY')
          DATE_VAL
  FROM ODF_CA_CID_FIN_CALENDAR
 WHERE CODE = TO_CHAR (SYSDATE, 'YYYYMMDD'))