SELECT
  INVESTMENTS.CODE INVESTMENT_ID,
  CC.UNIQUE_NAME COST_CENTER
FROM
  WARM01.INV_INVESTMENTS INVESTMENTS,
  WARM01.INV_PROJECTS PROJECTS,
  WARM01.PAC_MNT_PROJECTS PROJECT_FINANCIALS,
  WARM01.DEPARTMENTS,
  (SELECT UNIT_ID, UNIQUE_NAME, NAME
     FROM WARM01.OBS_UNITS_V
    WHERE DEPTH = 5 AND UNIT_MODE = 'OBS_UNIT_AND_ANCESTORS') CC
WHERE
  INVESTMENTS.ID = PROJECT_FINANCIALS.ID
  AND INVESTMENTS.ID = PROJECTS.PRID
  AND PROJECT_FINANCIALS.DEPARTCODE = DEPARTMENTS.DEPARTCODE
  AND DEPARTMENTS.OBS_UNIT_ID = CC.UNIT_ID
  AND PROJECT_FINANCIALS.CLASS IN ('BASELINE')
  AND PROJECTS.IS_TEMPLATE = 0;