SELECT
  P.PRSTART,
  P.PRFINISH,
  R.FULL_NAME RESOURCE_NAME,
  S.FULL_NAME SUBMITTED_BY,
  M.FULL_NAME MANAGER_NAME,
  T.PRMODTIME,
  T.POSTED_TIME
FROM 
  PRTIMESHEET T,
  PRTIMEPERIOD P,
  SRM_RESOURCES R,
  SRM_RESOURCES S,
  SRM_RESOURCES M
WHERE 
  T.PRTIMEPERIODID = P.PRID
  AND T.PRRESOURCEID = R.ID
  AND T.PRSUBMITTEDBY = S.USER_ID(+)
  AND R.MANAGER_ID = M.USER_ID(+)
  AND T.PRMODTIME > TO_DATE('06022011','MMDDYYYY') 
  AND T.PRTIMEPERIODID IN (5000009,5000017,5000025,5000026)