SELECT 
  W.TRANSNO,
  W.PROJECT_CODE, 
  W.ENTRYDATE, 
  W.TRANSDATE, 
  W.QUANTITY, 
  V.TOTALCOST,
  W.NOTES, 
  W.ENTRY_RESOURCE_CODE,
  R.FULL_NAME ENTRY_RESOURCE_NAME
FROM 
  PPA_WIP W,
  PPA_WIP_VALUES V,
  SRM_RESOURCES R
WHERE 
  W.TRANSNO = V.TRANSNO
  AND V.CURRENCY_TYPE = 'HOME'
  AND W.ENTRY_RESOURCE_CODE = R.UNIQUE_NAME
  AND W.ENTRY_RESOURCE_CODE NOT IN 'admin' 
  AND W.PROJECT_CODE = 'HC2'